services:
  pyspark:
    image: jupyter/pyspark-notebook:x86_64-ubuntu-22.04
    container_name: pyspark
    ports:
      - "8888:8888" 
    # environment:
    #   - SPARK_MODE=master
    #   - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #   - SPARK_RPC_ENCRYPTION_ENABLED=no
    #   - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #   - SPARK_SSL_ENABLED=no
    volumes:
      - ./etl:/home/jovyan/etl
      - ./Functions:/home/jovyan/Functions
      
    env_file:
      - .env