services:
  pyspark:
    build: .
    container_name: pyspark
    ports:
      - "8888:8888" 
    # environment:
    #   - SPARK_MODE=master
    #   - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #   - SPARK_RPC_ENCRYPTION_ENABLED=no
    #   - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #   - SPARK_SSL_ENABLED=no
    volumes:
      - ./etl:/opt/spark/etl
      - ./Functions:/opt/spark/Functions
      
    env_file:
      - .env